name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: make gradle wrapper executable
        working-directory: ./workspace
        run: chmod +x ./gradlecw
      - name: build
        working-directory: ./workspace
        run: ./gradlecw build
      - name: Release
        working-directory: ./workspace
        uses: softprops/action-gh-release@v1
        with:
          files: |
            WCFabric/build/libs/*
            WCForge/build/libs/*

      - name: Publish-Forge-Curseforge
        working-directory: ./workspace
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 521594
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}  
          loaders: forge
          name: ${{github.ref_name}} - Forge
          version-type: beta
          files: '*Forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
      - name: Publish-Forge-Modrinth
        working-directory: ./workspace
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: kYuIpRLv
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}} - Forge
          files: '*Forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
      - name: Publish-Fabric
        working-directory: ./workspace
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: kYuIpRLv
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 521594
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}  
          loaders: fabric
          name: ${{github.ref_name}} - Fabric
          files: '*Fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'